browser/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

app_name = 'browser'
urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name="browser/home.html")),
    url(r'^home$', TemplateView.as_view(template_name="browser/home.html"), name='home'),
    url(r'^about$', TemplateView.as_view(template_name="browser/about.html"), name='about'),
    url(r'^search$', views.search_gtin, name='search'),
    url(r'^search/(?P<gtin>[0-9a-z-]+)$', views.search_gtin2, name='search2'),
    url(r'^brand/list$', views.ViewBrandList.as_view(), name='brand_list'),
    url(r'^stats$', views.ViewStats.as_view(), name='stats'),
    url(r'^brand/(?P<bsin>[a-zA-Z0-9]+)$', views.ViewBsin.as_view(), name='bsin'),
    url(r'^gtin/(?P<pk>[0-9a-z-]+)$', views.ViewGtin.as_view(), name='gtin'),
    url(r'^result/(?P<gtin>[0-9]+)$', views.ViewResultGtin.as_view(), name='result'),
    url(r'^owner/list$', views.ViewOwnerList.as_view(), name='owner_list'),
    url(r'^owner/(?P<owner>[a-zA-Z0-9]+)$', views.ViewOwner.as_view(), name='owner'),
    url(r'^label/list$', views.ViewLabelList.as_view(), name='label_list'),
    url(r'^label/(?P<pk>[0-9]+)$', views.ViewLabel.as_view(), name='label'),
    url(r'^orga/list$', views.ViewOrgaList.as_view(), name='orga_list'),
    url(r'^orga/(?P<pk>[0-9]+)$', views.ViewOrga.as_view(), name='orga'),
]

eggs/urls.py
from django.conf.urls import include,url
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	url(r'^', include('browser.urls')),
    url(r'^adminamoi/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

browser/models.py
from django.db import models
from django.core.validators import RegexValidator
import uuid
from django_extensions.db.fields import UUIDField

def get_brand_default():
    return 'ZZZZZZ'

def get_color_default():
    return 1

# Gtin contains products with a GTIN-13
class Gtin(models.Model):
    GTIN_ID = UUIDField(default=uuid.uuid4, editable=False, primary_key=True)
    GTIN_CD = models.CharField(max_length=13, validators=[RegexValidator(regex='^.{13}$', message='Length has to be 13', code='nomatch')], null=True, blank=True)
    GCP_CD = models.ForeignKey('Gs1_gcp', null=True, blank=True)
    BSIN = models.ForeignKey('Brand', default=get_brand_default)
    CAT_CD = models.ForeignKey('Category', null=True, blank=True, default=1)
    PKG_UNIT = models.IntegerField(default=0, null=True, blank=True)
    PACKAGING_CD = models.ForeignKey('Packaging', null=True, blank=True)
    METHOD_CD = models.ForeignKey('Method', null=True, blank=True)
    SIZE_CD = models.ForeignKey('Size', null=True, blank=True)
    GRADE_CD = models.ForeignKey('Grade', null=True, blank=True)
    COLOR_CD = models.ForeignKey('Color', null=True, blank=True, default=get_color_default)
    FED_CD = models.ForeignKey('Fed', null=True, blank=True)
    LABEL_CD = models.ManyToManyField('Label', blank=True)
    def __str__(self):
        return self.GTIN_CD
    class Meta:
        ordering = ('METHOD_CD','SIZE_CD','GTIN_CD', )
# Using multi table inheritance - automaticly creates one to one field
#class GtinPackagingDetail(Gtin):
#    PACKAGING_2_CD = models.ForeignKey('Packaging', null=True, blank=True)

class Label(models.Model):
    LABEL_CD = models.AutoField(primary_key=True)
    LABEL_NM = models.CharField(max_length=255)
    LABEL_COUNTRY_ISO = models.ForeignKey('Country', null=True, blank=True)
    LABEL_DESC = models.TextField(null=True, blank=True)
    LABEL_LINK = models.CharField(max_length=255, null=True, blank=True)
    LABEL_WIKI_EN = models.CharField(max_length=255, null=True, blank=True)
    def __str__(self):
        return u'%s - %s' % (self.LABEL_COUNTRY_ISO, self.LABEL_NM )
    class Meta:
        ordering = ('LABEL_COUNTRY_ISO', 'LABEL_NM',)

class Color(models.Model):
    COLOR_CD = models.AutoField(primary_key=True)
    COLOR_NM = models.CharField(max_length=255)
    COLOR_DESC = models.TextField(null=True, blank=True)
    def __str__(self):
        return u'%s' % (self.COLOR_NM )

class Fed(models.Model):
    FED_CD = models.AutoField(primary_key=True)
    FED_NM = models.CharField(max_length=255)
    FED_DESC = models.TextField(null=True, blank=True)
    def __str__(self):
        return u'%s' % (self.FED_NM )


class Size(models.Model):
    SIZE_CD = models.AutoField(primary_key=True)
    SIZE_NM = models.CharField(max_length=255)
    SIZE_SIZE_NM = models.CharField(max_length=255,null=True, blank=True)
    SIZE_DESC = models.TextField(null=True, blank=True)
    def __str__(self):
        return u'%s' % (self.SIZE_NM )
    class Meta:
        ordering = ('SIZE_NM', )

class Grade(models.Model):
    GRADE_CD =  models.AutoField(primary_key=True)
    GRADE_NM = models.CharField(max_length=255)
    GRADE_SHORT_NM = models.CharField(max_length=255,null=True, blank=True)
    GRADE_DESC = models.TextField(null=True, blank=True)
    def __str__(self):
        return u'%s' % (self.GRADE_NM)

class Method(models.Model):
    METHOD_CD = models.AutoField(primary_key=True)
    METHOD_NM = models.CharField(max_length=255)
    METHOD_ISO = models.ForeignKey('Country', null=True, blank=True)
    METHOD_DESC = models.TextField(null=True, blank=True)
    METHOD_LEVEL_CD = models.IntegerField(null=True, blank=True)
    def __str__(self):
        return u'%s - %s' % (self.METHOD_ISO, self.METHOD_NM)
    class Meta:
        ordering = ('METHOD_ISO', 'METHOD_NM',)

class Packaging(models.Model):
    PACKAGING_CD = models.AutoField(primary_key=True)
    PACKAGING_NM = models.CharField(max_length=255)
    PACKAGING_LINK = models.CharField(max_length=255,null=True, blank=True)
    def __str__(self):
        return u'%s - %s' % (self.PACKAGING_CD, self.PACKAGING_NM)

class Category(models.Model):
    CAT_CD = models.AutoField(primary_key=True)
    CAT_NM = models.CharField(max_length=255)
    CAT_LINK = models.CharField(max_length=255,null=True, blank=True)
    def __str__(self):
        return u'%s - %s' % (self.CAT_CD, self.CAT_NM)

class Brand(models.Model):
    BSIN = models.CharField(max_length=6, primary_key=True)
    BRAND_NM = models.CharField(max_length=255)
    BRAND_TYPE_CD = models.ForeignKey('Brand_type', null=True, blank=True)
    BRAND_LINK = models.CharField(max_length=255, null=True, blank=True)
    BRAND_COUNTRY_ISO = models.ForeignKey('Country')
    OWNER_CD = models.ForeignKey('Owner', null=True, blank=True)
    BRAND_OPEN = models.NullBooleanField(default=False, null=True, blank=True)
    BRAND_DISPLAY = models.NullBooleanField(default=True, null=True, blank=True)

    def __str__(self):
        return u'%s - %s' % (self.BRAND_NM, self.BSIN)

    class Meta:
        ordering = ('BRAND_NM', )

class Brand_type(models.Model):
    BRAND_TYPE_CD = models.AutoField(primary_key=True)
    BRAND_TYPE_NM = models.CharField(max_length=255, null=True, blank=True)
    def __str__(self):
        return self.BRAND_TYPE_NM

class Owner(models.Model):
    OWNER_CD = models.AutoField(primary_key=True)
    OWNER_NM = models.CharField(max_length=255, null=True, blank=True)
    OWNER_LINK = models.CharField(max_length=255, null=True, blank=True)
    OWNER_COUNTRY_ISO = models.ForeignKey('Country')
    OWNER_WIKI_EN = models.CharField(max_length=255, null=True, blank=True)
    def __str__(self):
        return u'%s - %s' % (self.OWNER_CD, self.OWNER_NM)
    class Meta:
        ordering = ('OWNER_NM', )

class Orga(models.Model):
    ORGA_CD = models.AutoField(primary_key=True)
    ORGA_NM = models.CharField(max_length=255, null=True, blank=True)
    ORGA_LINK = models.CharField(max_length=255, null=True, blank=True)
    ORGA_COUNTRY_ISO = models.ForeignKey('Country')
    ORGA_WIKI_EN = models.CharField(max_length=255, null=True, blank=True)
    def __str__(self):
        return u'%s - %s' % (self.ORGA_CD, self.ORGA_NM)
    class Meta:
        ordering = ('ORGA_NM', )


class Gs1_gcp(models.Model):
    GCP_CD = models.CharField(max_length=13, primary_key=True)
    GLN_CD = models.CharField(max_length=13,null=True, blank=True)
    GLN_NM = models.CharField(max_length=255,null=True, blank=True)
    GLN_ADDR_02 = models.CharField(max_length=38,null=True, blank=True)
    GLN_ADDR_03 = models.CharField(max_length=38,null=True, blank=True)
    GLN_ADDR_04 = models.CharField(max_length=38,null=True, blank=True)
    GLN_ADDR_POSTALCODE = models.CharField(max_length=38,null=True, blank=True)
    GLN_ADDR_CITY = models.CharField(max_length=38)
    GLN_COUNTRY_ISO_CD = models.CharField(max_length=38)
    CONTACT_NAME = models.CharField(max_length=38,null=True, blank=True)
    CONTACT_TEL = models.CharField(max_length=255,null=True, blank=True)
    CONTACT_HOTLINE = models.CharField(max_length=255, null=True, blank=True)
    CONTACT_FAX = models.CharField(max_length=255,null=True, blank=True)
    CONTACT_MAIL = models.CharField(max_length=255,null=True, blank=True)
    CONTACT_WEB = models.CharField(max_length=255,null=True, blank=True)
    GLN_LAST_CHANGE = models.CharField(max_length=10,null=True, blank=True)
    GLN_PROVIDER = models.CharField(max_length=13,null=True, blank=True)
    SEARCH_GTIN_CD = models.CharField(max_length=13,null=True, blank=True)
    GEPIR_GCP_CD = models.CharField(max_length=13,null=True, blank=True)
    ADD_PARTY_ID = models.CharField(max_length=13,null=True, blank=True)
    RETURN_CODE = models.ForeignKey('Gs1_gcp_rc', null=True, blank=True)
    SOURCE = models.CharField(max_length=100)
    SYNC_DT = models.DateField(null=True, blank=True)
    def __str__(self):
        return u'%s - %s' % (self.GCP_CD, self.GLN_NM)
    class Meta:
        ordering = ('GCP_CD', )

class Gs1_gcp_rc(models.Model):
    RETURN_CODE = models.CharField(max_length=3, primary_key=True)
    RETURN_NAME = models.CharField(max_length=255)
    ORIGIN = models.CharField(max_length=255)
    def __str__(self):
        return u'%s - %s' % (self.RETURN_CODE, self.RETURN_NAME)

class Country(models.Model):
    COUNTRY_ISO = models.CharField(max_length=2, primary_key=True)
    COUNTRY_NM_U = models.CharField(max_length=80)
    COUNTRY_NM_L = models.CharField(max_length=80)
    COUNTRY_EU = models.NullBooleanField(default=False, null=True, blank=True)
    def __str__(self):
        return u'%s - %s' % (self.COUNTRY_ISO, self.COUNTRY_NM_U)
    class Meta:
        ordering = ('COUNTRY_ISO', )

# Search is used to store gtin that people are searching and the number of times it has been searched
class Search(models.Model):
    GTIN_CD = models.CharField(max_length=13, primary_key=True)
    SEARCH_NB =  models.IntegerField(default=1)

# same but for the API
class Search_api(models.Model):
    GTIN_CD = models.CharField(max_length=13, primary_key=True)
    SEARCH_NB =  models.IntegerField(default=1)

browser/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.conf import settings

from .models import Gtin, Brand, Owner, Search, Label, Orga
from django.db.models import Count

# --------------------------------------------------------------------
#  WEBSITE BROWSER
# --------------------------------------------------------------------
import requests

def search_gtin(request):

    if request.POST['gtin']:
        gtin_in = request.POST['gtin']
        if len(gtin_in) == 8 or len(gtin_in) == 12 or len(gtin_in) == 13:
            if len(gtin_in) == 8:
                gtin_in = '00000' + gtin_in
            if len(gtin_in) == 12:
                gtin_in = '0' + gtin_in
        else:
            return render(request, 'browser/home.html', {
                'error_message': "Please enter 8, 12 or 13 digits",
            })
    else:
        return render(request, 'browser/home.html', {
            'error_message': "please enter a correct gtin code",
        })

    if Search.objects.filter(pk=gtin_in).exists():
        search_gtin = Search.objects.get(pk=gtin_in)
        search_gtin.SEARCH_NB += 1
        search_gtin.save()
    else:
        new_entry = Search(GTIN_CD = gtin_in, SEARCH_NB = 1)
        new_entry.save()

    try:
            gtin = Gtin.objects.get(GTIN_CD=gtin_in)
    except (KeyError, Gtin.DoesNotExist):
        return render(request, 'browser/gtin-error.html', {
            'gtin': gtin_in,
        })
    else:
        return HttpResponseRedirect(reverse('browser:result', args=(gtin.GTIN_CD,)))

def search_gtin2(request,gtin):

    if gtin:
        gtin_in = gtin
        if len(gtin_in) == 8 or len(gtin_in) == 12 or len(gtin_in) == 13:
            if len(gtin_in) == 8:
                gtin_in = '00000' + gtin_in
            if len(gtin_in) == 12:
                gtin_in = '0' + gtin_in
        else:
            return render(request, 'browser/home.html', {
                'error_message': "Please enter 8, 12 or 13 digits",
            })
    else:
        return render(request, 'browser/home.html', {
            'error_message': "please enter a correct gtin code",
        })

    if Search.objects.filter(pk=gtin_in).exists():
        search_gtin = Search.objects.get(pk=gtin_in)
        search_gtin.SEARCH_NB += 1
        search_gtin.save()
    else:
        new_entry = Search(GTIN_CD = gtin_in, SEARCH_NB = 1)
        new_entry.save()

    try:
            gtin = Gtin.objects.get(GTIN_CD=gtin_in)
    except (KeyError, Gtin.DoesNotExist):
        return render(request, 'browser/gtin-error.html', {
            'gtin': gtin_in,
        })
    else:
        return HttpResponseRedirect(reverse('browser:result', args=(gtin.GTIN_CD,)))

class ViewResultGtin(generic.ListView):
    template_name = 'browser/gtin-result.html'
    context_object_name = 'gtin_list'
    model = Gtin

    def get_queryset(self):
        gtin = self.kwargs['gtin']
        return Gtin.objects.filter(GTIN_CD=gtin)


class ViewGtin(generic.DetailView):
    template_name = 'browser/gtin.html'
    model = Gtin

    queryset = Gtin.objects.all()

    def get_object(self):
        object = super(ViewGtin, self).get_object()
        if object.GTIN_CD and object.GTIN_CD[0:1] == "0":
            object.UPC_CD = object.GTIN_CD[1:12]
        object.save()
        return object

class ViewBrandList(generic.ListView):
    template_name = 'browser/brand_list.html'
    context_object_name = 'page_brand_list'
    model = Brand

    def get_queryset(self):
        return Brand.objects.filter(BRAND_DISPLAY=True).order_by('BRAND_COUNTRY_ISO','BRAND_NM')

class ViewBsin(generic.ListView):
    template_name = 'browser/bsin.html'
    context_object_name = 'gtin_list'
    model = Gtin

    def get_context_data(self, **kwargs):
        context = super(ViewBsin, self).get_context_data(**kwargs)
        context.update({
            'bsin_detail': Brand.objects.get(pk=self.kwargs['bsin']),
            #'gtin_count' : Gtin.objects.values('GCP_CD__GLN_COUNTRY_ISO_CD').annotate(dcount=Count('GTIN_CD'))
        })
        return context

    def get_queryset(self):
        bsin = self.kwargs['bsin']
        return Gtin.objects.filter(BSIN=bsin).order_by('METHOD_CD','PKG_UNIT','SIZE_CD')


class ViewStats(generic.ListView):
    template_name = 'browser/stats.html'
    context_object_name = 'stats_data'
    model = Gtin

    def get_context_data(self, **kwargs):
        context = super(ViewStats, self).get_context_data(**kwargs)
        context.update({
            'gtin_total_count' : Gtin.objects.aggregate(Count('GTIN_CD')),
            'gtin_count' : Gtin.objects.values('GCP_CD__GLN_COUNTRY_ISO_CD').annotate(dcount=Count('GRADE_CD')).order_by('dcount')
        })
        return context

    def get_queryset(self):
        return Gtin.objects.values('GCP_CD__GLN_COUNTRY_ISO_CD').annotate(dcount=Count('GTIN_CD'))


class ViewOwnerList(generic.ListView):
    template_name = 'browser/owner_list.html'
    context_object_name = 'owner_list'
    model = Owner

    def get_queryset(self):
        """Return the last five published questions."""
        return Owner.objects.order_by('OWNER_COUNTRY_ISO','OWNER_NM')

class ViewOwner(generic.ListView):
    template_name = 'browser/owner.html'
    context_object_name = 'brand_list'
    model = Brand

    def get_context_data(self, **kwargs):
        context = super(ViewOwner, self).get_context_data(**kwargs)
        context.update({
            'owner_detail': Owner.objects.get(pk=self.kwargs['owner']),
        })
        return context

    def get_queryset(self):
        owner = self.kwargs['owner']
        return Brand.objects.filter(OWNER_CD=owner).order_by('BRAND_NM')



class ViewLabelList(generic.ListView):
    template_name = 'browser/label_list.html'
    context_object_name = 'label_list'
    model = Label

    def get_queryset(self):
        return Label.objects.order_by('LABEL_COUNTRY_ISO','LABEL_NM')

class ViewLabel(generic.DetailView):
    template_name = 'browser/label.html'
    model = Label

    queryset = Label.objects.all()

class ViewOrgaList(generic.ListView):
    template_name = 'browser/orga_list.html'
    context_object_name = 'orga_list'
    model = Orga

    def get_queryset(self):
        return Orga.objects.order_by('ORGA_COUNTRY_ISO','ORGA_NM')

class ViewOrga(generic.DetailView):
    template_name = 'browser/orga.html'
    model = Orga

    queryset = Orga.objects.all()

# --------------------------------------------------------------------
#   REST API DRF
# --------------------------------------------------------------------

# gtin for test : 0836093401314    0857063002652

browser/templates/browser/base.html
<!DOCTYPE html>
<html lang="en" prefix="og: http://ogp.me/ns#">
{% load static %}
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
		<meta name="description" content="This website is a prototype to demonstrate that barcode can be used as an effective tool for individual consumers to make informed purchase decision beyond the messages manufactures and marketers put in front of us">
		<meta name="keywords" content="">
    <meta name="author" content="Philippe Plagnol">

    <meta property="og:url" content="https://egg-scan.herokuapp.com/">
    <meta property="og:site_name" content="Egg Scan Project" >
    <meta property="og:title" content="Egg Scan Project" >
    <meta property="og:description" content="Barcode can be used as an effective tool for individual consumers to make informed purchase decision" >
    <meta property="og:type" content="website" >
    <meta property="og:author" content='https://egg-scan.herokuapp.com/' >
    <meta property="og:image" content="http://egg-scan.herokuapp.com/static/browser/img/logo-egg-scan-project.jpg" >
    <meta property="og:image:width" content="400" >
    <meta property="og:image:height" content="400" >

    <meta property="twitter:card" content="summary_large_image" >
    <meta property="twitter:site" content="@eggscanproject" >
    <meta property="twitter:creator" content='Egg Scan Project' >
    <meta property="twitter:title" content="Egg Scan Project" >
    <meta property="twitter:description" content="Barcode can be used as an effective tool for individual consumers to make informed purchase decision" >
    <meta property="twitter:image:src" content="http://egg-scan.herokuapp.com/static/browser/img/logo-egg-scan-project.jpg" >
    <meta property="twitter:image:width" content="400" >
    <meta property="twitter:image:height" content="400" >

		<link rel="icon" href="{% static 'browser/img/favicon.png' %}">
    <meta name="google-site-verification" content="W_YhMEYih_ggtjzgyolC14lPwkxLBNu_397F97PrmUQ" />

    <title>Egg Scan Project</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'browser/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'browser/css/flags.css' %}" rel="stylesheet">

    <script src="//netdna.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'browser/css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'browser/css/style.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static 'browser/js/ie-emulation-modes-warning.js' %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'browser:home' %}">Egg Scan Project</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li {% if request.get_full_path == '/brand/list' %}class="active"{% endif %}><a href="{% url 'browser:brand_list' %}">Brands</a></li>
            <li {% if request.get_full_path == '/label/list' %}class="active"{% endif %}><a href="{% url 'browser:label_list' %}">Labels</a></li>
            <li {% if request.get_full_path == '/orga/list' %}class="active"{% endif %}><a href="{% url 'browser:orga_list' %}">Organizations</a></li>
            <li {% if request.get_full_path == '/stats' %}class="active"{% endif %}><a href="{% url 'browser:stats' %}">Stats</a></li>
            <li {% if request.get_full_path == '/about' %}class="active"{% endif %}><a href="{% url 'browser:about' %}">About</a></li>
          </ul>
          <!-- add search form -->
          <form class="navbar-form navbar-right" role="search" action="{% url 'browser:search' %}" method="post">
            {% csrf_token %}
              <div class="form-group">
                  <input name="gtin" type="text" class="form-control" placeholder="Search this site" required="">
              </div>
              <div class="form-group">

                  <button type="submit" class="btn btn-success">
                  <span class="glyphicon glyphicon-search"></span>
                  </button>

              </div>
          </form>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <!-- Begin page content -->

{% block content %}{% endblock %}

		    <footer class="footer">
		      <div class="container">
						<p class="text-muted">
							Egg Scan Project - 2016
					 </p>
		      </div>
		    </footer>


		    <!-- Bootstrap core JavaScript
		    ================================================== -->
		    <!-- Placed at the end of the document so the pages load faster -->
		    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
		    <script>window.jQuery || document.write('<script src="{% static 'browser/js/jquery.min.js' %}"><\/script>')</script>
		    <script src="{% static 'browser/js/bootstrap.min.js' %}"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.min.js"></script>
		    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
		    <script src="{% static 'browser/js/menu.cssie10-viewport-bug-workaround.js' %}"></script>
		  </body>
		</html>

browser/templates/browser/brand_list.html
{% extends "browser/base.html" %}
{% load static %}
{% block content %}

<div class="container">
	<div class="page-header">
		<h1>Select a brand to see its products</h1>
	</div>

{% if page_brand_list %}
<section class="row">

	{% regroup page_brand_list by BRAND_COUNTRY_ISO as country_list %}

	<div class="list-item2">
	{% for page_brand_list in country_list %}

			<div class="col-xs-12 col-sm-12 col-md-12">
				<h2>
					{% if page_brand_list.grouper.COUNTRY_EU %}
					<img align="center" src="{% static 'browser/img/flag_48/EU.png' %}" >
					{% endif %}
					<img align="center" src="{% with 'browser/img/flag_48/'|add:page_brand_list.grouper.COUNTRY_ISO|add:'.png' as image_static %}{% static image_static %}{% endwith %}" >
					{{ page_brand_list.grouper.COUNTRY_NM_L }}
				</h2>
				<hr>
			</div>
				{% for Brand in page_brand_list.list %}
					<div class="col-xs-6 col-sm-3 col-md-2">

						<a href="{{ Brand.BSIN }}">
							<img 	class="thumbnail-list"
										src="{% static "" %}browser/img/brand/{{Brand.BSIN}}.jpg"
										title="Brand - {{ Brand.BRAND_NM }}"
										alt="Brand - {{ Brand.BRAND_NM }}"
										width="150" height="150"
							 >
							 <!-- 							onerror="this.src='{% static 'browser/img/coming-soon.jpg' %}';" -->
						</a>
					</div>
			  {% endfor %}

	{% endfor %}
	</div>
</section>
{% else %}
	<p>No brands are available.</p>
{% endif %}
</div>
</div>
{% endblock %}

browser/templates/browser/gtin-error.html
{% extends "browser/base.html" %}
{% load static %}
{% block content %}

<div class="container">
	<div class="page-header">
    <h1>The code {{ gtin }} not in the database</h1>
  </div>
	<p>
	Could you please send an picture of the product (one full and one with the barcode) on the following email address  ? <br>
	<b>egg.scan.project@gmail.com</b>
</p>

	Thanks in advance :)

</div>

{% endblock %}

browser/templates/browser/gtin-result.html
{% extends "browser/base.html" %}
{% load static %}
{% load browser_extras %}
{% block content %}

  {% if gtin_list.count > 0 %}

    {% for gtin in gtin_list %}
      {% include "browser/gtin.html" %}
    {% endfor %}

    {{gtin_list.count}} Result

  {% endif %}

{% endblock %}